#!/usr/bin/env python
"""
    Executes a local script upon receiving a message on a specific Amazon SNS topic

    Command Line:
    
        jldexec topic /path/to/script
    

    @author: Jean-Lou Dupont
"""
import logging, os, sys, argparse
op=os.path

try:
    import jldaws
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldaws

########################################################################

DESC="Executes script based on SNS message received on a specific topic"
DEFAULTS={
          "polling_interval": 30
          ,
          }

def main():
    import jldaws.do_checks
    import jldaws.do_setup
    
    parser=argparse.ArgumentParser(description=DESC)
    parser.add_argument('topic',       nargs=1, help="Topic to subscribe to")
    parser.add_argument('module_name', nargs=1, help="Python module name to execute 'run' callable")
    parser.add_argument('-p', type=int, dest="polling_interval", action="store", help="Polling interval", default=DEFAULTS["polling_interval"])
    args=parser.parse_args()
    
    from jldaws.script_exec import run
    run(args)

try:
    sys.exit(main())
    
except KeyboardInterrupt:
    logging.info("..Exiting")
    sys.exit(0)##no probs
    
except Exception,e:
    logging.error(str(e))
    sys.exit(1)
