#!/usr/bin/env python
"""
    S3 Notify - calls the "run" function of a python module upon detecting changes to an S3 bucket

    Command Line:
    
        jlds3notify [-p POLLING_INTERVAL] [-r prefix] bucket_name module_name
    
        where 'prefix' is a usual S3 bucket prefix
        where 'bucket_name' is the S3 bucket to monitor
        where 'module_name' is the python module to call the 'run' function

    'Run' function signature:
    
        run(bucket_name, prefix, keys={}, changes=[])
               
        where 'keys' is a dictionary with the key field being the S3 object name
         and the value field being a boto.s3.Key object
         
        where 'changes' is a list of S3 object name which changed between polling interval

    @author: Jean-Lou Dupont
"""
import os, sys, argparse
op=os.path

try:
    import jldaws
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldaws

########################################################################

DESC="Amazon S3 tools"
DEFAULTS={
          "polling_interval": 30
          ,
          }

def main():
    try:
        import jldaws.do_setup
        import logging
        import jldaws.do_checks
        
        parser=argparse.ArgumentParser(description=DESC)
        parser.add_argument('bucket_name',    type=str, help="Bucket name")
        parser.add_argument('module_name',    type=str, help="Python module to use")
        parser.add_argument('-r',             dest="prefix", help="Prefix", type=str, action="store", default=None)
        parser.add_argument('-d',             dest="enable_debug",     action="store_true", help="Enable debug information")
        parser.add_argument('-p',             dest="polling_interval", type=int, action="store", help="Polling interval (seconds)", default=DEFAULTS["polling_interval"])        
        args=parser.parse_args()
        
        from jldaws.script_s3notify import run
        run(args)

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())