#!/usr/bin/env python
"""
    SDB utils

    @author: Jean-Lou Dupont
"""
__version__="0.1"
import os, sys, argparse
op=os.path

try:
    if os.environ["JLDDEV"]: raise
    import jldaws #@UnusedImport
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldaws #@UnusedImport

########################################################################

DESC="""SDB utilities - version %s
""" % __version__
DEFAULTS={
          }

def main():
    try:
        import jldaws.do_setup  #@UnusedImport
        import logging
        import jldaws.do_checks #@UnusedImport
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@', formatter_class=argparse.RawTextHelpFormatter)
        
        parser.add_argument('-dn',  dest='domain_name',     type=str, help="Domain name (for create, delete)",   default=None)
        parser.add_argument('-ld',  dest='domains_list',    action="store_true", help="List all domains",   default=False)
        parser.add_argument('-dd',  dest='domain_delete',   action="store_true", help="Delete domain",      default=False)
        parser.add_argument('-cd',  dest='domain_create',   action="store_true", help="Create domain",      default=False)
        
        from jldaws.script_sdb import run
        from jldaws.tools_sys import process_command_line
        args=process_command_line(parser)
        run(**args)

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        
sys.exit(main())
