#!/usr/bin/env python
"""
    Transmit JSON object to an SQS queue

    Command Line:
    
        jldtxsqs [-f] queue_name
    
        This command takes its input from stdin and passes the received json string to stdout + to SQS queue

    @author: Jean-Lou Dupont
"""
import os, sys, argparse
op=os.path

try:
    import jldaws
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldaws

########################################################################

DESC="Send JSON object to an SQS queue"
DEFAULTS={
          }

def main():
    try:
        import jldaws.do_setup
        import logging
        import jldaws.do_checks
        
        parser=argparse.ArgumentParser(description=DESC)
        parser.add_argument('queue_name', type=str, help="SQS queue name to send to")
        parser.add_argument('-f',         dest="flush_queue", action="store_true", help="Flush SQS queue at startup")
        args=parser.parse_args()
        
        from jldaws.script_txsqs import run
        run(args)

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())